version: '3'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - redis
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code

  redis:
    image: "redis:latest"
