# Generated by Django 4.2.5 on 2023-09-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='room',
            new_name='room_name',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
