# Generated by Django 4.2.5 on 2023-09-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_room_chatmessage_room_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='description',
        ),
    ]
