# Generated by Django 4.2.5 on 2023-09-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friend_accepted_at_alter_friend_friend_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set(),
        ),
    ]
